#!/usr/bin/python

import sys
from mod_pbxproj import XcodeProject

if sys.argv[2] == 'iPhone':
	project = XcodeProject.Load(sys.argv[1] + '/Unity-iPhone.xcodeproj/project.pbxproj')
	project.add_file('System/Libray/Frameworks/StoreKit.framework', tree='SDKROOT')
	project.add_file('System/Libray/Frameworks/AdSupport.framework', tree='SDKROOT')
	project.save()
