#!/usr/bin/perl 

# Searches for other PostprocessBuildPlayer scripts and executes them. Make sure the other script 
# have a name suffix with an underscore "_" like "PostprocessBuildPlayer_AnotherBuild" or whatever. 
# Starts off by executing a global UpdateXCodeWithRequirements.scrpt.
# 
# Based on script by Rob Terrell, rob@stinkbot.com 
# 

use File::Glob ':glob';

# Run the global libraries script
$installPath = $ARGV[0];
$currDir = `pwd`;
chomp $currDir;

# Grab all the PostprocessBuildPlayer files
@files = bsd_glob( "Assets/Editor/postprocessbuildplayer_*", GLOB_NOCASE );

foreach $file( @files )
{
	if( !( $file =~ m/\./ ) )
	{
		system( "chmod", "755", $file );
		print "PostProcessBuildPlayer: calling " . $file . "\n"; 
		system( $file, $ARGV[0], $ARGV[1], $ARGV[2], $ARGV[3], $ARGV[4], $ARGV[5], $ARGV[6] );
	}
}